### ISSUE TITLE
Исправить доп. задание 2

### ISSUE THREAD

**Issue by blockin90** [SergeiK99/laba5#2]
до сих пор пропускает выражения вида: `http://www.--------.----------.ru`

**Comment by SergeiK99** [comment]
![8nWAd4Dqe0M](https://user-images.githubusercontent.com/114760845/210650824-73f8a9d8-0163-4453-97e6-0ca02d53abb4.jpg)
Я ничего не менял, решил проверить работу и оно не пропускает данное выражение (может я неправильно понял)

**Comment by SergeiK99** [comment]
Я ничего не менял, решил проверить работу и оно не пропускает данное выражение (может я неправильно понял)
![8nWAd4Dqe0M](https://user-images.githubusercontent.com/114760845/210652477-6067c186-691b-4c0a-8bfd-e5d8c40f4bc5.jpg)
