### ISSUE TITLE
Исправить регулярки для проверки адресов

### ISSUE THREAD

**Issue by blockin90** [SergeiK99/laba5#3]
Из задачи https://github.com/SergeiK99/laba5/issues/2 : 

        Я ничего не менял, решил проверить работу и оно не пропускает данное выражение (может я неправильно понял)
![8nWAd4Dqe0M](https://user-images.githubusercontent.com/114760845/210652477-6067c186-691b-4c0a-8bfd-e5d8c40f4bc5.jpg)

_Originally posted by @SergeiK99 in https://github.com/SergeiK99/laba5/issues/2#issuecomment-1371437565_
      

судя по коду выводятся только адреса, прошедшие проверку, и т.к. адрес http://www.--------.----------.ru есть в выводе программы, он прошел проверку регулярным выражением, но подобные адреса не являются допустимыми, они не могут состоять только из символов -. Соответственно регулярка пропускать его не должна

**Comment by SergeiK99** [comment]
![image](https://user-images.githubusercontent.com/114760845/210811629-92d45231-10f9-47c3-a3c5-a394c73265eb.png)
Ну вроде же оно, если я все правильно понимаю или не понимаю саму суть
