### ISSUE TITLE
5й пункт задания

### ISSUE THREAD

**Issue by blockin90** [SergeiK99/laba5#5]
Выполнение 5го пункта предполагалось выполнять и показывать очно. Цитата из задания: `5.	Используя текстовый редактор, поддерживающий регулярные выражения, например Notepad++ или Visual Studio, выполните следующие действия над файлом «Лабораторная работа 5 - testData.xml»... `

т.к. сейчас с этим проблема, предлагаю сделать мини отчет в вордовском файле с описанием всего что происходит, либо в комментах к этой задаче описать порядок действий (со скринами и т.п.)

p.s. на днях обновил текст 5й лабы - добавил туда немного про работу с регулярками в notepad++, можно обновить репозиторий, посмотреть, если сейчас непонятно как это делать

**Comment by SergeiK99** [comment]
Задание a) Вариант 4 задания 1. Вставил регулярное выражение сделанное в лабораторной.
![image](https://user-images.githubusercontent.com/114760845/210835424-da825d60-5dfd-462d-8c21-3b2e2f4e6fda.png)
Задание b) Удаление нумерации строк. ^-начало строки \d - 0-9 + - 1 и более раз \. - точка
![image](https://user-images.githubusercontent.com/114760845/210837649-6130ffda-af01-4d5c-9eaf-a27db6273cda.png)
Задание c)  и b) - не получается, всю голову уже сломал...
